@startuml "Erd"


' --- Actor ---

entity "User" as user { 
    * id: int <PK>
    * role_id: int <FK>
    ---
    * name: string
    * username: string <U>
    * password: string
    * status: int
    email: string <U>
    phone_number: string <13>
    birth_place: string
    birth_date: date
    gender: int
    address: string
}

entity "Role" as role {
    * id: int <PK>
    ---
    * name: string
    * code: string <U>
}

entity "Lecturer" as lecturer {
    * id: int <PK>
    * study_program_pk: int <PK>
    ---
    * nip: string
    * code: string <U>
}

entity "Student" as student {
    * id: int <PK>
    * study_program_id: int <FK>
    ---
    * nim: string
    * generation: year  
}

entity "ClassLeader" as class_leader {
    * id: int <PK>
    ---
}

entity LabAssistant {
    * id: int <PK>
    --- 
    * tns: string
}



' Main

entity "Department" as department {
    * id: int <PK>
    ---
    * name: string
    * code: string <U>
}

entity "StudyProgram" as study_program {
    * id: int <PK>
    * department_id: int <FK>
    ---
    * name: string
    * code: string <U>
}

entity "Course" as course {
    * id: int <PK>
    ---
    * name: string
    * sks: int
} 

entity "Attendance" as attendance {
    * id: int <PK>
    * user_id: <FK>
    * class_id: <FK>
    schedule_id: <FK>
    ---
    * status: int
}

entity "FacilityRequest" as facility_request {
    * id: int <PK>
    ---
    * date: date 
}

entity "Facility" as facility {
    * id: int <PK>
    * request_id: int <FK>
    ---
    * name: string
    * code: string <U>
    * status: int
}

entity ScheduleRequest {
    * id: int <PK>
    * user_id: int <FK>
    ---
    * status: int    
}

entity "Schedule" as schedule {
    * id: int <PK>
    * room_id: int <FK>
    sr_id: int <FK>
    course_id: int <FK>
    ---
    * start_datetime: datetime
    * end_datetime: datetime
    * status: int
    * campus: int
    information: string
}

entity AttendanceMonitoring {
    * id: int <PK>
    * schedule_id: int <FK>
    ---
    topic: string
    sub_topic: string
}

entity "Class" as class {
    * id: int <PK>
    cl_id: int <FK>
    ---
    * name: string
    * code: string <U>
}

entity "Room" as room {
    * id: int <PK>
    ---
    * status: int
    * name: string
    * code: string <U>
}

entity Computer {
    * id : int
    ---
    * computer_count: int
    * name : string
    * processor : string
    * gpu : string
    * ram_capacity : int
    * ram_type : int
    * storage_type : int
    * storage_capacity : int
    * display_size : float
    * display_resolution : int
    * display_refresh_rate : int
    * os : string
    * release_year : int
    * category : int
}

entity Application {
    * id: int <PK>
    ---
    * name: string
}

' StudyProgram and Department

department ||--|{ study_program
lecturer ||--|| study_program
student ||--|| study_program

' Roles

user ||--|{ role

user |o--o| lecturer: "Inherit"
user |o--o| student: "Inherit"
student |o--o{ class_leader: "Inherit"
student |o--o{ LabAssistant: "Inherit"



' class

student }|--|{ class: ""
lecturer }|--|{ class: ""
class_leader ||--|| class: ""

' Schedule

user ||--|{ ScheduleRequest
ScheduleRequest ||--|{ schedule
lecturer }|--|{ schedule: ""
student }|--|{ schedule: ""
room ||--||schedule: ""
class ||--|{ schedule:""
course ||--|{ schedule:""
schedule ||--|| AttendanceMonitoring

' Attendanceu

user ||--|{ attendance: ""
schedule ||--|{ attendance: ""

' Course

LabAssistant }|--|| course
lecturer }|--|{ course: ""
student }|--|{ course: ""
course ||--|| class

' Room

room ||--|{ Computer
room ||--|{ Application

' Facility
user ||--|{ facility_request
facility_request ||--|{ facility


@enduml